umi_tools dedup \
	-I ${bam} \
	-S ${bam.baseName}.dedup.bam \
	-L ${bam.baseName}_dedup.log \
	--spliced-is-unique \
	--per-gene \
	--per-contig \
	--per-cell \
	--extract-umi-method tag \
	--umi-tag=UR \
	--cell-tag=CB \
	--read-length \
	--no-sort-output
